### ISSUE TITLE
Error en el repositorio por defecto

### ISSUE THREAD

**Issue by ferbercedo** [ferbercedo/unizar-vv-catmedit#1]
La ubicación del repositorio por defecto apuntaba a una ruta inexistente.
(« E:\workspacesEclipse\workspace\catmdeditOpenSource\CatMDEditOpenSource\
repository\metadata »)
/cc @ferbercedo @Guillerm097

**Comment by MLopez97** [comment]
Es una incidencia antigua y ya ha sido resuelta.
