### ISSUE TITLE
Comprobación de existencia de tesauros

### ISSUE THREAD

**Issue by ferbercedo** [ferbercedo/unizar-vv-catmedit#10]
**Describe the bug**
Falta EPSG

**To Reproduce**
Visualizar los tesauros incluidos en la versión (EUROVOC, AGROVOC, EPSG, GEMET y otros según el proyecto) en distintos idiomas. Comprobar que no falta ninguno de los que debería estar.

**Expected behavior**
 todos los tesauros necesarios están accesibles

**Desktop (please complete the following information):**
 - OS: Windows 7
cc/ @Guillerm097 @ferbercedo

**Comment by miguel-latre** [comment]
Es un duplicado de #9. Cerradlo añadiendo la etiqueta _«duplicate»_.
