### ISSUE TITLE
Comprobación de exportación a formatos específicos

### ISSUE THREAD

**Issue by Guillerm097** [ferbercedo/unizar-vv-catmedit#11]
**Describe the bug**
Da error unicamente al exportar a ISO excel.

**To Reproduce**
Realizar exportaciones de metadatos ISO19119  a formatos específicos:
- De ISO19119 a ISO19119 (xml, HTML)

**Expected 
Exportación del metadato a todos los formatos posibles.

**Desktop (please complete the following information):**

/cc @Guillerm097 @ferbercedo

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
