### ISSUE TITLE
Comprobación de actualización entre editores

### ISSUE THREAD

**Issue by ferbercedo** [ferbercedo/unizar-vv-catmedit#12]
**Describe the bug**
La mala visualización de las ventanas y su editor hace difícil su comprobación

**To Reproduce**
Comprobar que al modificar un campo en un editor ISO, dicha modificación se ve reflejada en el resto de los editores

**Expected behavior**
 Actualización de metadatos en todos los editores

**Desktop (please complete the following information):**
 - OS: Windows 7
cc/ @MLopez97 @ferbercedo

**Comment by Guillerm097** [comment]
No se encuentra el error.
