### ISSUE TITLE
Mostrar opción sobre el tamaño de la letra

### ISSUE THREAD

**Issue by MLopez97** [ferbercedo/unizar-vv-catmedit#13]
**Is your feature request related to a problem? Please describe.**
No aparecen indicaciones en ningún momento sobre cómo modificar el tamaño de letra. Puede que haya usuarios que necesiten un tamaño de letra más grande.

**Describe the solution you'd like**
Mostrar una opción sobre el aumento del tamaño de la letra.

**Describe alternatives you've considered**
En Herramientas, definir un tamaño de letra modificable por defecto.

**Comment by Guillerm097** [comment]
No hace falta cambiarla.
