### ISSUE TITLE
Comprobación de exportación a formatos específicos

### ISSUE THREAD

**Issue by Guillerm097** [ferbercedo/unizar-vv-catmedit#14]
**Describe the bug**
Da error unicamente al exportar a ISO excel.

**To Reproduce**
Realizar exportaciones de metadatos Dublin Core a formatos específicos:
- De DC a ISO19115 (xml, HTML, excel…)
- De DC a FGDC (xml, HTML)
- De DC a DC (xml, HTML)

**Expected behavior**
Exportación del metadato a todos los formatos posibles

**Desktop (please complete the following information):**
 - OS: Ubuntu

/cc @Guillerm097 @MLopez97

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
