### ISSUE TITLE
Comprobación de actualización entre editores

### ISSUE THREAD

**Issue by ferbercedo** [ferbercedo/unizar-vv-catmedit#15]
**Describe the bug**
La mala visualización de las ventanas y su editor hace difícil su comprobación

**To Reproduce**
Comprobar que al modificar un campo en un editor, dicha modificación se ve reflejada en el resto de los editores (si hubiera más de uno)

**Expected behavior**
actualización de metadatos en todos los editores

**Desktop (please complete the following information):**
 - OS: Windows 10
cc/ @Guillerm097 @ferbercedo

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
