### ISSUE TITLE
Comprobación de etiquetas, textos y tooltips en varios idiomas

### ISSUE THREAD

**Issue by Guillerm097** [ferbercedo/unizar-vv-catmedit#3]
**Describe the bug**
Cuando se establece el checo, polaco o francés como idioma no todas las etiquetas aparecen en dicho idioma. 

**To Reproduce**
Navegar por los menús y ventanas de la herramienta, visualizar las etiquetas de la aplicación, incluyendo los textos que definen cada elemento de metadatos, ejemplos, etc. Prestar especial atención a etiquetas de diálogos que se abren solo a petición del usuario. Pasar el puntero por encima de los elementos de metadatos del árbol. Comprobar en varios idiomas.

**Expected behavior**
A clear and concise description of what you expected to happen

**Desktop (please complete the following information):**
 - OS: [Ubuntu]

/cc @Guillerm097  @MLopez97

**Comment by miguel-latre** [comment]
En el enunciado de la práctica se pedía que cerrarais los defectos.
Al cerrarlos, asignad la etiqueta _«duplicate»_, _«invalid»_ o _«wontfix»_ que estiméis más adecuada.
En el contexto de la realización de la práctica, podéis considerar que una incidencia consiste en un defecto inválido cuándo no estéis de acuerdo con la definición del defecto que se haya hecho y que es _«wontfix»_ en el resto de los casos, ya que no vais a corregirlos.
