### ISSUE TITLE
Etiquetas, textos y tooltips en varios idiomas

### ISSUE THREAD

**Issue by ferbercedo** [ferbercedo/unizar-vv-catmedit#4]
**Describe the bug**
Cuando se establece el Checo como idioma, no todas las etiquetas aparecen en Checo. Ocurre lo mismo con el francés o el polaco. 

**To Reproduce**
1. Navegar por los menús y ventanas de la herramienta.
2. Visualizar las etiquetas de la aplicación.
3. Comprobar en varios idiomas.

**Expected behavior**
Etiquetas existentes, definiciones y ejemplos completos y tooltips completos.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
