### ISSUE TITLE
Comprobación de Menú Ayuda

### ISSUE THREAD

**Issue by Guillerm097** [ferbercedo/unizar-vv-catmedit#5]
**Describe the bug**
No se abre la ventana de abrir recurso.

**To Reproduce**
Seleccionar un metadato que contenga la ruta de acceso al dato en sí mismo y pulsar sobre la opción "abrir recurso".

**Expected behavior**
- Acceso al manual actualizado y al "Acerca de" de la versión

**Desktop (please complete the following information):**
 - OS: Ubuntu

/cc @Guillerm097 @ferbercedo

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
