### ISSUE TITLE
Ventanas emergentes

### ISSUE THREAD

**Issue by MLopez97** [ferbercedo/unizar-vv-catmedit#6]
**Is your feature request related to a problem? Please describe.**
No es un error, pero es una mejora ya que puede agobiar al usuario.

**Describe the solution you'd like**
Controlar la frecuencia y el número de ventanas emergentes.

**Describe alternatives you've considered**
Eliminar por completo las ventanas emergentes o mostrarlas en una esquina y de una en una.

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
