### ISSUE TITLE
Comprobar el funcionamiento del visor de datos

### ISSUE THREAD

**Issue by ferbercedo** [ferbercedo/unizar-vv-catmedit#7]
**Describe the bug**
Aparece una ventana de advertencia comunicando que no existe ningún recurso.

**To Reproduce**
Seleccionar un metadato que contenga la ruta de acceso al dato en sí mismo y pulsar sobre la opción "abrir recurso"

**Expected behavior**
acceso a un visor de datos que permita consultar el dato vinculado al metadato  

**Desktop (please complete the following information):**
 - OS: [Windows 7

cc/ @MLopez97 @ferbercedo

**Comment by Guillerm097** [comment]
No hace falta corregirlo.

**Comment by Guillerm097** [comment]
No hace falta corregirlo.
