### ISSUE TITLE
Comprobar el funcionamiento del visor de datos

### ISSUE THREAD

**Issue by Guillerm097** [ferbercedo/unizar-vv-catmedit#8]
**Describe the bug**
Funciona pero a la hora de seleccionar una plantilla no te aparece el nombre.

**To Reproduce**
Lanzar CatMDEdit. Es necesario tener al menos una plantilla de metadatos creada.

**Expected behavior**
- repositorio de una colección de metadatos creado 

**Desktop (please complete the following information):**
 - OS: Ubuntu

/cc @Guillerm097 @MLopez97

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
