### ISSUE TITLE
Comprobación de existencia de tesauros

### ISSUE THREAD

**Issue by Guillerm097** [ferbercedo/unizar-vv-catmedit#9]
**Describe the bug**
Falta EPSG.

**To Reproduce**
Visualizar los tesauros incluidos en la versión (EUROVOC, AGROVOC, EPSG, GEMET y otros según el proyecto) en distintos idiomas. Comprobar que no falta ninguno de los que debería estar.

**Expected behavior**
Todos los tesauros necesarios están accesibles

**Desktop (please complete the following information):**
 - OS: Ubuntu

@Guillerm097 @ferbercedo

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.
